version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      timezone: 'America/Chicago'
    commit-message:
      prefix: "chore(deps)"
    labels: ["github_actions", "dependencies"]
    groups:
      dependencies:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
