---
name: "Auto Labeler"
on:
  workflow_call:
    inputs:
      config-name:
        required: true
        type: string
    secrets:
      github-token:
        required: true
permissions:
  contents: read
jobs:
  main:
    permissions:
      pull-requests: write
    name: Auto label pull requests
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit
      - uses: release-drafter/release-drafter/autolabeler@44a942e465867c7465b76aa808ddca6e0acae5da # v7.1.0
        with:
          config-name: ${{ inputs.config-name }}
          token: ${{ secrets.github-token }}
