---
name: "Pull Request Labeler"
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      github-token:
        required: true
permissions:
  contents: read
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/labeler@v6.0.1
        with:
          configuration-path: ${{ inputs.config-path }}
          repo-token: "${{ secrets.github-token }}"
