## Reference: https://github.com/amannn/action-semantic-pull-request
---
name: "Lint PR Title"
on:
  workflow_call:
    inputs:
      types:
        required: false
        type: string
        default: |
          build
          chore
          ci
          docs
          feat
          fix
          perf
          refactor
          revert
          style
          test
      scopes:
        required: false
        type: string
        default: ""
      requireScope:
        required: false
        type: boolean
        default: false
    secrets:
      github-token:
        required: true
jobs:
  main:
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@7f33ba792281b034f64e96f4c0b5496782dd3b37
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        with:
          types: ${{ inputs.types }}
          scopes: ${{ inputs.scopes }}
          requireScope: ${{ inputs.requireScope }}
