---
name: "Release"

on:
  workflow_call:
    inputs:
      publish:
        required: false
        type: boolean
        default: true
      release-config-name:
        required: true
        type: string
    secrets:
      github-token:
        required: true
    outputs:
      full-tag:
        description: 'Full tag of release'
        value: ${{ jobs.create_release.outputs.full-tag }}
      short-tag:
        description: 'Short tag of release'
        value: ${{ jobs.create_release.outputs.short-tag }}
      body:
        description: 'Body content of release'
        value: ${{ jobs.create_release.outputs.body }}

permissions:
  contents: read

jobs:
  create_release:
    # release if
    # manual deployment OR
    # merged to main and labelled with release labels
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event.pull_request.merged == true &&
      (contains(github.event.pull_request.labels.*.name, 'breaking') ||
      contains(github.event.pull_request.labels.*.name, 'feature') ||
      contains(github.event.pull_request.labels.*.name, 'vuln') ||
      contains(github.event.pull_request.labels.*.name, 'release')))
    outputs:
      full-tag: ${{ steps.release-drafter.outputs.tag_name }}
      short-tag: ${{ steps.get_tag_name.outputs.SHORT_TAG }}
      body: ${{ steps.release-drafter.outputs.body }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        with:
          config-name: ${{ inputs.release-config-name }}
          publish: ${{ inputs.publish }}
      - name: Get the Short Tag
        id: get_tag_name
        run: |
          short_tag=$(echo ${{ steps.release-drafter.outputs.tag_name }} | cut -d. -f1)
          echo "SHORT_TAG=$short_tag" >> "$GITHUB_OUTPUT"
