## Reference: https://github.com/amannn/action-semantic-pull-request
---
name: "Test Lint PR Title"
on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
permissions:
  contents: read
jobs:
  lint_pr_title:
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    uses: ./.github/workflows/pr-title.yaml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
