## Reference: https://github.com/amannn/action-semantic-pull-request
---
name: "Test Lint PR Title"
on:
  # pull_request_target event is required for autolabeler to support all PRs including forks
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
permissions:
  contents: read
jobs:
  lint_pr_title:
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    uses: ./.github/workflows/pr-title.yaml
    with:
      types: |
        build
        chore
        ci
        docs
        feat
        fix
        perf
        refactor
        revert
        style
        test
      scopes: |
        ci
        docs
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
