---
name: "Test Pull Request Labeler"
on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
permissions:
  contents: read
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/labeler.yaml
    with:
      config-path: .github/labeler.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
