---
name: "Test Pull Request Labeler"
on:
  pull_request_target:
permissions:
  contents: read
jobs:
  labeler:
    uses: ./.github/workflows/labeler.yaml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
