---
name: "Test Release"
on:
  workflow_dispatch:
  # pull_request_target event is required for autolabeler to support all PRs including forks
  pull_request_target:
    types: [closed]
    branches: [main]
jobs:
  release:
    permissions:
      contents: write
      pull-requests: read
    uses: ./.github/workflows/release.yaml
    with:
      publish: true
      release-config-name: release-drafter.yaml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  release_image:
    needs: release
    permissions:
      contents: write
      discussions: write
      packages: write
      pull-requests: read
    uses: ./.github/workflows/release-image.yaml
    with:
      image-name: github/ospo-reusable-workflows
      full-tag: ${{ needs.release.outputs.full-tag }}
      short-tag: ${{ needs.release.outputs.short-tag }}
      create-attestation: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      image-registry: ghcr.io
      image-registry-username: ${{ github.actor }}
      image-registry-password: ${{ secrets.GITHUB_TOKEN }}
  release_discussion:
    needs: release
    permissions:
      contents: read
      discussions: write
    uses: ./.github/workflows/release-discussion.yaml
    with:
      full-tag: ${{ needs.release.outputs.full-tag }}
      body: ${{ needs.release.outputs.body }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      discussion-repository-id: ${{ secrets.DISCUSSION_REPOSITORY_ID }}
      discussion-category-id: ${{ secrets.DISCUSSION_CATEGORY_ID }}
